# Generated by Django 3.2.20 on 2023-07-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.URLField()),
                ('pickup_location', models.CharField(blank=True, max_length=50)),
                ('pickup_address', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('upfront_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mileage', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
