# Generated by Django 3.2.20 on 2023-08-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('sku', models.CharField(blank=True, default='', max_length=150)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('main_image', models.URLField()),
                ('products_id', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('keywords', models.CharField(blank=True, default='', max_length=255)),
                ('short_desc', models.TextField(blank=True, default='')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.TextField(blank=True, default='')),
                ('cleaned_description', models.TextField(blank=True, default='')),
                ('image_urls', models.TextField(blank=True, default='[]')),
                ('breadcrumbs', models.TextField(blank=True, default='[]')),
                ('discount_tiers', models.CharField(blank=True, default='[]', max_length=100)),
                ('discount_amount', models.CharField(blank=True, default='[]', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.data')),
            ],
        ),
    ]
