# Generated by Django 3.2.20 on 2023-08-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='breadcrumbs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='discount_amount',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='discount_tiers',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='image_urls',
            field=models.TextField(blank=True, default=''),
        ),
    ]
