# Generated by Django 4.2.2 on 2023-07-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scrapshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="additional_images",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scrapshop.additionalimage",
            ),
            preserve_default=False,
        ),
    ]
