# Generated by Django 4.2.2 on 2023-07-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scrapshop", "0002_product_additional_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="additional_images",
        ),
        migrations.AddField(
            model_name="additionalimage",
            name="products",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scrapshop.product",
            ),
            preserve_default=False,
        ),
    ]
