# Generated by Django 3.2.20 on 2023-08-20 18:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('selector', models.CharField(max_length=300)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('homepage', models.URLField()),
                ('sitemap_url', models.URLField()),
                ('first_crawl', models.DateTimeField(auto_now=True)),
                ('last_crawl', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.website')),
            ],
        ),
        migrations.CreateModel(
            name='DJItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('link', models.URLField()),
                ('sku', models.CharField(blank=True, default='', max_length=150)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('main_image', models.URLField()),
                ('products_id', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('keywords', models.CharField(blank=True, default='', max_length=255)),
                ('short_desc', models.TextField(blank=True, default='')),
                ('price', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('cleaned_description', models.TextField(blank=True, default='')),
                ('discount_tiers', models.CharField(default='', max_length=100)),
                ('discount_amount', models.CharField(default='', max_length=100)),
                ('crawl_data', models.JSONField()),
                ('image_urls', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pages.additionalimage')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
