# Generated by Django 3.2.20 on 2023-08-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djitem',
            name='crawl_data',
            field=models.JSONField(blank=True),
        ),
    ]
