# Generated by Django 3.2.20 on 2023-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_djitem_crawl_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djitem',
            name='image_urls',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
