# Generated by Django 3.2.20 on 2023-08-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_djitem_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='djitem',
            name='breadcrumbs',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='djitem',
            name='discount_amount',
            field=models.CharField(blank=True, default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='djitem',
            name='discount_tiers',
            field=models.CharField(blank=True, default='[]', max_length=100),
        ),
    ]
