# Generated by Django 3.2.20 on 2023-08-22 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230820_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djitem',
            name='image_urls',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pages.additionalimage'),
        ),
        migrations.AlterField(
            model_name='djitem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.manufacturer'),
        ),
        migrations.AlterField(
            model_name='djitem',
            name='products_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
