# Generated by Django 3.2.20 on 2023-08-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20230822_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djitem',
            name='crawl_data',
        ),
    ]
